import type { ParsedQuestion } from "@/lib/universal-parser";

export const GATE_SCIENTIFIC_QUESTIONS: ParsedQuestion[] = [
  {
    questionText: `The resistance values of the Wheatstone bridge shown are: $P = 2000\\ \\Omega$, $Q = 500\\ \\Omega$, $R = 3000\\ \\Omega$. The battery voltage $E = 50\\text{V}$. The battery has an internal resistance of $1\\ \\Omega$ and the Galvanometer (G) has a resistance of $50\\ \\Omega$.\n\nThe value of the resistance $S$ for balanced condition is ________ $\\Omega$.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 750,
    numericalTolerance: 0,
    numericalUnit: "Ω",
    explanation: "Under balanced bridge condition, the ratio of opposite branches is equal: $P / Q = R / S$. Therefore, $2000 / 500 = 3000 / S \\implies 4 = 3000 / S \\implies S = 3000 / 4 = 750\\ \\Omega$.",
    imageUrl: "/circuit/wheatstone.svg",
    year: 2026,
    unit: 1,
    include: true,
  },
  {
    questionText: `A system with two generators G1 and G2 (without generator limits) is shown. The total load on the system is $1184\\text{ MW}$. The expressions for the cost of generation ($C_1$ and $C_2$) and real power loss ($P_{Loss}$) are as follows:\n\n$C_1(P_{G1}) = 1000 + 50 P_{G1} + 0.01 (P_{G1})^2\\text{ Rs/MWh}$\n$C_2(P_{G2}) = 2000 + 50 P_{G2} + 0.001 (P_{G2})^2\\text{ Rs/MWh}$\n$P_{Loss} = 0.001 (P_{G2} - 50)^2\\text{ MW}$\n\nWhen the generators are operating at their optimal generation, meeting the total load requirement, the real power loss in the system is _________ MW.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 5.8,
    numericalTolerance: 0.1,
    numericalUnit: "MW",
    explanation: "Consider the Lagrange multiplier $\\lambda = 70.25$ for optimal generation. Real power loss in the system is calculated based on optimal generator dispatch parameters which yields $5.8\\text{ MW}$.",
    imageUrl: "/circuit/generators.svg",
    year: 2026,
    unit: 2,
    include: true,
  },
  {
    questionText: `A balanced three-phase supply is given to a $30\\text{ kW}, 4\\text{-pole}, 400\\text{ V}, 50\\text{ Hz}$, wound rotor induction motor with Y-connected stator and rotor windings. The motor is driving a constant torque load. With shorted sliprings, the machine runs at $1476\\text{ rpm}$.\n\nWhen an external non-inductive resistance of $0.27\\ \\Omega$ per phase is connected in series in the rotor circuit, the steady-state speed drops to $1404\\text{ rpm}$. Neglecting rotational losses, the actual per phase rotor winding resistance is _______ $\\Omega$.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 0.54,
    numericalTolerance: 0.01,
    numericalUnit: "Ω",
    explanation: "In an induction motor, torque is proportional to $s / r$. Since load torque is constant, $s_1 / r_1 = s_2 / r_2$. Synchronous speed $N_s = 120 \\times 50 / 4 = 1500\\text{ rpm}$. Initial slip $s_1 = (1500 - 1476)/1500 = 0.016$. Second slip $s_2 = (1500 - 1404)/1500 = 0.064$. Thus, $s_1 / R_r = s_2 / (R_r + R_{ext}) \\implies 0.016 / R_r = 0.064 / (R_r + 0.27) \\implies R_r = 0.54\\ \\Omega$.",
    imageUrl: null,
    year: 2026,
    unit: 3,
    include: true,
  },
  {
    questionText: `Consider the two-port network shown. For maximum power transfer to the resistive load ($R_L$), the value of $R_L$ should be ________ $\\Omega$.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 12.0,
    numericalTolerance: 0.2,
    numericalUnit: "Ω",
    explanation: "For maximum power transfer, the load resistance $R_L$ must equal the Thevenin resistance of the network looking back from the terminals. Deactivating the independent 10V source (short circuit) and calculating the equivalent resistance yields $12.0\\ \\Omega$.",
    imageUrl: "/circuit/two-port.svg",
    year: 2026,
    unit: 4,
    include: true,
  },
  {
    questionText: `Consider the circuit shown. Assume that the diode ($D$) is ideal. Given $v_s = 100 \\sin(2\\pi 50t)\\text{ V}$, $V_{dc} = 50\\text{ V}$, and $R = 10\\ \\Omega$, the average value of the current through the diode is _________ A.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 1.13,
    numericalTolerance: 0.02,
    numericalUnit: "A",
    explanation: "The diode conducts only when $v_s > V_{dc} \\implies 100 \\sin(\\omega t) > 50 \\implies \\omega t \\in [\\pi/6, 5\\pi/6]$. The average current is calculated as $\\frac{1}{2\\pi R} \\int_{\\pi/6}^{5\\pi/6} (100\\sin(\\theta) - 50) d\\theta = 1.13\\text. A$.",
    imageUrl: "/circuit/diode.svg",
    year: 2026,
    unit: 5,
    include: true,
  },
  {
    questionText: `The magnitude of the contour integral $\\oint_C \\left(\\frac{(z+1)^2}{(z-i)(z-2)}\\right) dz$ over the contour $C: |z - 2 - i| = 3/2$ is ________.\n\nNote: $z$ is a complex variable and $i = \\sqrt{-1}$.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 8.24,
    numericalTolerance: 0.02,
    numericalUnit: "",
    explanation: "Using Cauchy's Residue Theorem. Only the pole at $z = 2$ lies inside the circle of radius 1.5 centered at $2+i$. The residue at $z=2$ is evaluated, multiplied by $2\\pi i$, taking the absolute magnitude to give $8.24$.",
    imageUrl: "/circuit/contour.svg",
    year: 2026,
    unit: 6,
    include: true,
  },
  {
    questionText: `A uniform spherical volume charge distribution of radius $2\\text{ m}$, centered at the origin, has a strength of $\\frac{3}{\\pi} \\times 10^{-6}\\text{ C/m}^3$. A point charge of strength $\\pi \\times 8.854 \\times 10^{-12}\\text{ C}$ is moved from $(-3, 0, -4)$ to $(0, 0, 4)$ in Cartesian coordinate system. The relative permittivity of the medium is $1$ and the coordinate values are in meters. The work done during the process is ________ $\\mu$J.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 24.0,
    numericalTolerance: 0.5,
    numericalUnit: "μJ",
    explanation: "The work done during the process of moving the point charge within the electrostatic field of the spherical charge is calculated based on potential difference between the end points, yielding $24.0\\ \\mu$J.",
    imageUrl: null,
    year: 2026,
    unit: 7,
    include: true,
  },
  {
    questionText: `Let X and Y be two real-valued random variables with $E(X) = 1, E(Y) = 2, E(X^2) = 4, E(Y^2) = 9$, and $E(XY) = 0.9$, where E denotes the expectation operator. The value of $\\alpha$ that minimizes $E((X - \\alpha Y)^2)$ is ________.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 0.1,
    numericalTolerance: 0,
    numericalUnit: "",
    explanation: "To minimize $f(\\alpha) = E(X^2) - 2\\alpha E(XY) + \\alpha^2 E(Y^2)$, differentiate with respect to $\\alpha$ and set to 0: $-2 E(XY) + 2\\alpha E(Y^2) = 0 \\implies \\alpha = E(XY)/E(Y^2) = 0.9 / 9 = 0.1$.",
    imageUrl: null,
    year: 2026,
    unit: 8,
    include: true,
  },
  {
    questionText: `The integral $\\frac{1}{\\pi}\\int_0^\\infty \\frac{x^{2026}}{(1+x^{2026})(1+x^2)}dx$ evaluates to ________.`,
    questionType: "numerical",
    options: [],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 0.25,
    numericalTolerance: 0.01,
    numericalUnit: "",
    explanation: "Using the substitution $x = 1/t$, the integral transforms symmetrically. Solving the integral results in exactly $0.25$.",
    imageUrl: null,
    year: 2026,
    unit: 9,
    include: true,
  },
  {
    questionText: `In the given figure, $\\overline{PQ}$ is the diameter of a circle with center $O$. Two points $R$ and $S$ are chosen on the circle such that $\\angle ROS = 80^\\circ$. When $\\overline{PR}$ and $\\overline{QS}$ are extended, they meet at $T$. The value of $\\angle RTS$ is _________.`,
    questionType: "mcq",
    options: ["40°", "50°", "60°", "80°"],
    correctIndex: 1,
    correctIndices: [],
    numericalAnswer: 0,
    numericalTolerance: 0,
    numericalUnit: "",
    explanation: "Since ROS = 80°, we find the angles at base, extended intersection T gives RTS = 50°.",
    imageUrl: "/circuit/geometry-circle.svg",
    year: 2026,
    unit: 10,
    include: true,
  },
  {
    questionText: `Based on the relationship between each polygon and the number inside it, the value of '$X$' is ________.`,
    questionType: "mcq",
    options: ["720", "596", "24", "240"],
    correctIndex: 0,
    correctIndices: [],
    numericalAnswer: 0,
    numericalTolerance: 0,
    numericalUnit: "",
    explanation: "The relationship represents side count factorials: Triangle (3!) = 6, Square (4!) = 24, Pentagon (5!) = 120, Hexagon (6!) = 720. Therefore, X = 720.",
    imageUrl: "/circuit/polygons.svg",
    year: 2026,
    unit: 11,
    include: true,
  },
];
